(()=>{'use strict';
const FALLBACK_BUILD='26.0.2-20260910.3';
const CSS=['/css/terminal.css','/css/uide.css'];
const JS=['/lib/rv64exec.js','/lib/posix-core.js','/lib/progress.js','/lib/apk.js','/lib/systemd.js','/lib/wayland.js','/lib/uide-core.js','/lib/uide-files.js','/lib/uide-terminal.js','/lib/uide-about.js','/lib/uide-wayland-ui.js','/lib/shell-runtime.js','/lib/shell-builtins.js','/lib/shell-fs-common.js','/lib/shell-fs-manage.js','/lib/shell-fs-inspect.js','/lib/shell-text.js','/lib/shell-system-info.js','/lib/shell-command-meta.js','/lib/shell-process-utils.js','/lib/shell-network.js','/lib/shell-entry.js'];
async function manifest(){try{let r=await fetch('/build.json?probe='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}catch{return{version:'26.0.2',build:FALLBACK_BUILD}}}
async function clearOriginCaches(){try{if('caches'in window)for(let k of await caches.keys())await caches.delete(k)}catch{}try{if('serviceWorker'in navigator)for(let r of await navigator.serviceWorker.getRegistrations())await r.unregister()}catch{}}
function addCss(url,build){let l=document.createElement('link');l.rel='stylesheet';l.href=url+'?v='+encodeURIComponent(build);document.head.append(l)}
function addScript(url,build){return new Promise((resolve,reject)=>{let s=document.createElement('script');s.src=url+'?v='+encodeURIComponent(build);s.onload=resolve;s.onerror=()=>{s.remove();let r=document.createElement('script');r.src=url+'?v='+encodeURIComponent(build)+'&fresh='+Date.now();r.onload=resolve;r.onerror=()=>reject(Error('failed loading '+url));document.body.append(r)};document.body.append(s)})}
async function boot(){let m=await manifest(),build=m.build||FALLBACK_BUILD,old='';try{old=localStorage.getItem('posixjs-build')||''}catch{}if(old&&old!==build){await clearOriginCaches();try{localStorage.setItem('posixjs-build',build)}catch{}let u=new URL(location.href);if(u.searchParams.get('posix-refresh')!==build){u.searchParams.set('posix-refresh',build);location.replace(u.toString());return}}else try{localStorage.setItem('posixjs-build',build)}catch{}window.POSIX_BUILD=build;CSS.forEach(x=>addCss(x,build));for(let x of JS)await addScript(x,build)}
boot().catch(e=>{let o=document.querySelector('#o');if(o)o.textContent+='BOOT ERROR: '+e.message+'\n';console.error(e)})})();
