(()=>{'use strict';
const FALLBACK_BUILD='26.0.3-20260910.3';
const CSS=['/css/terminal.css','/css/uide.css','/css/labs.css','/css/designs.css'];
const COMMANDS=['help','clear','pwd','cd','ls','cat','echo','mkdir','find','apk','uide','systemctl','journalctl','sync','uname','whoami','sudo','sl','exec','touch','rm','rmdir','cp','mv','ln','head','tail','basename','dirname','stat','readlink','tree','wc','sort','printf','seq','date','uptime','hostname','env','id','du','df','which','type','history','true','false','sleep','fetch','status','designs','labs','grep','base64','realpath','cksum','uniq','cut','tac','rev','update'];
const JS=['/lib/rv64exec.js','/lib/rv64c.js','/lib/rv64a.js','/lib/posix-core.js','/lib/update-manager.js','/lib/progress.js','/lib/apk.js','/lib/systemd.js','/lib/wayland.js','/lib/nerdfont.js','/lib/designs.js','/lib/labs-mobile.js','/lib/uide-core.js','/lib/uide-mobile.js','/lib/uide-files.js','/lib/uide-terminal.js','/lib/uide-about.js','/lib/uide-developer.js','/lib/uide-wayland-ui.js','/lib/shell-runtime.js','/lib/shell-fs-common.js',...COMMANDS.map(x=>'/lib/commands/'+x+'.js'),'/lib/shell-entry.js'];
async function manifest(){try{let r=await fetch('/build.json?probe='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}catch{return{version:'26.0.3',build:FALLBACK_BUILD}}}
async function clearOriginCaches(){try{if('caches'in window)for(let k of await caches.keys())await caches.delete(k)}catch{}try{if('serviceWorker'in navigator)for(let r of await navigator.serviceWorker.getRegistrations())await r.unregister()}catch{}}
function addCss(url,build){let l=document.createElement('link');l.rel='stylesheet';l.href=url+'?v='+encodeURIComponent(build);document.head.append(l)}
function addScript(url,build){return new Promise((resolve,reject)=>{let s=document.createElement('script');s.src=url+'?v='+encodeURIComponent(build);s.onload=resolve;s.onerror=()=>{s.remove();let r=document.createElement('script');r.src=url+'?v='+encodeURIComponent(build)+'&fresh='+Date.now();r.onload=resolve;r.onerror=()=>reject(Error('failed loading '+url));document.body.append(r)};document.body.append(s)})}
async function boot(){let m=await manifest(),build=m.build||FALLBACK_BUILD,old='';try{old=localStorage.getItem('posixjs-build')||''}catch{}if(old&&old!==build){await clearOriginCaches();try{localStorage.setItem('posixjs-build',build)}catch{}let u=new URL(location.href);if(u.searchParams.get('posix-refresh')!==build){u.searchParams.set('posix-refresh',build);location.replace(u.toString());return}}else try{localStorage.setItem('posixjs-build',build)}catch{}window.POSIX_BUILD=build;CSS.forEach(x=>addCss(x,build));for(let x of JS)await addScript(x,build)}
boot().catch(e=>{let o=document.querySelector('#o');if(o)o.textContent+='BOOT ERROR: '+e.message+'\n';console.error(e)})})();
