(()=>{'use strict';
const KEY='posixjs-labs-mobilemode';
let root=null,shift=false,symbols=false,ctrl=false;
const enabled=()=>{try{return localStorage.getItem(KEY)==='1'}catch{return false}};
const setStored=v=>{try{localStorage.setItem(KEY,v?'1':'0')}catch{}};
const shell=()=>window.POSIXShell;
const input=()=>document.querySelector('#c');
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
function selection(){const I=input();let s=Number.isFinite(I?.selectionStart)?I.selectionStart:I?.value.length||0,e=Number.isFinite(I?.selectionEnd)?I.selectionEnd:s;return{I,s,e}}
function replace(text){const{I,s,e}=selection();if(!I)return;I.value=I.value.slice(0,s)+text+I.value.slice(e);const p=s+text.length;try{I.setSelectionRange(p,p)}catch{}refreshPreview()}
function move(delta,extend=false){const{I,s,e}=selection();if(!I)return;const base=delta<0?s:e,p=clamp(base+delta,0,I.value.length);try{I.setSelectionRange(extend?s:p,p)}catch{}refreshPreview()}
function homeEnd(end){const{I}=selection();if(!I)return;const p=end?I.value.length:0;try{I.setSelectionRange(p,p)}catch{}refreshPreview()}
function backspace(){const{I,s,e}=selection();if(!I)return;if(s!==e)return replace('');if(s>0){I.value=I.value.slice(0,s-1)+I.value.slice(e);try{I.setSelectionRange(s-1,s-1)}catch{}refreshPreview()}}
function del(){const{I,s,e}=selection();if(!I)return;if(s!==e)return replace('');if(s<I.value.length){I.value=I.value.slice(0,s)+I.value.slice(s+1);try{I.setSelectionRange(s,s)}catch{}refreshPreview()}}
function dispatch(key){const I=input();if(!I)return;I.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}))}
function sendKey(key){const I=input(),S=shell();if(!I||!S)return;if(key==='ENTER'){dispatch('Enter');return}if(key==='UP'||key==='DOWN'){dispatch(key==='UP'?'ArrowUp':'ArrowDown');setTimeout(refreshPreview,0);return}if(key==='LEFT'){move(-1);return}if(key==='RIGHT'){move(1);return}if(key==='HOME'){homeEnd(false);return}if(key==='END'){homeEnd(true);return}if(key==='BACKSPACE'){backspace();return}if(key==='DELETE'){del();return}if(key==='TAB'){replace('  ');return}if(key==='ESC'){I.value='';refreshPreview();return}if(key==='CTRL'){ctrl=!ctrl;render();return}if(key==='SHIFT'){shift=!shift;render();return}if(key==='SYMBOLS'){symbols=!symbols;shift=false;render();return}if(key==='CTRL-C'){S.out('^C');I.value='';S.prompt();refreshPreview();return}if(key==='CTRL-L'){S.O.textContent='';S.prompt();return}let text=key;if(ctrl){ctrl=false;if(String(key).toLowerCase()==='c'){S.out('^C');I.value='';S.prompt();render();refreshPreview();return}if(String(key).toLowerCase()==='l'){S.O.textContent='';S.prompt();render();return}}if(shift&&/^[a-z]$/.test(text)){text=text.toUpperCase();shift=false;render()}replace(text)}
function button(label,key=label,cls=''){const b=document.createElement('button');b.type='button';b.textContent=label;b.className=cls;b.tabIndex=-1;b.addEventListener('pointerdown',e=>{e.preventDefault();sendKey(key)});return b}
function makeRow(items,cls=''){const r=document.createElement('div');r.className='pmk-row '+cls;for(const item of items){if(Array.isArray(item))r.append(button(item[0],item[1],item[2]||''));else r.append(button(item))}return r}
function preview(){let p=root?.querySelector('.pmk-preview');if(!p)return null;return p}
function refreshPreview(){const p=preview(),I=input();if(!p||!I)return;const pos=Number.isFinite(I.selectionStart)?I.selectionStart:I.value.length;p.textContent=(I.value||' ')+'\n'+' '.repeat(Math.min(pos,120))+'▲'}
function renderKeys(){const body=root.querySelector('.pmk-body');body.textContent='';const tools=makeRow([['ls','ls '],['cd','cd '],['pwd','pwd'],['clear','clear'],['../','../'],['~/','~/'],['/','/'],['-','-'],['_','_'],['|','|'],['>','>'],['&&','&& ']],'pmk-tools');body.append(tools);if(symbols){body.append(makeRow(['1','2','3','4','5','6','7','8','9','0']));body.append(makeRow(['!','@','#','$','%','^','&','*','(',')']));body.append(makeRow(['-','_','=','+','[',']','{','}','\\','|']));body.append(makeRow([';',':',"'",'"',',','.','<','>','/','?']));}else{body.append(makeRow(['1','2','3','4','5','6','7','8','9','0']));for(const row of ['qwertyuiop','asdfghjkl','zxcvbnm'])body.append(makeRow([...row].map(ch=>[shift?ch.toUpperCase():ch,ch])))}body.append(makeRow([['Ctrl','CTRL',ctrl?'active':''],['⇧','SHIFT',shift?'active':''],[symbols?'ABC':'#+=','SYMBOLS'],['←','LEFT'],['→','RIGHT'],['Home','HOME'],['End','END'],['Tab','TAB'],['Space',' ','pmk-space'],['⌫','BACKSPACE'],['Del','DELETE'],['Enter','ENTER','pmk-enter']],'pmk-special'));body.append(makeRow([['Ctrl-C','CTRL-C'],['Ctrl-L','CTRL-L'],['Esc','ESC'],['↑','UP'],['↓','DOWN']],'pmk-nav'))}
function render(){if(!root)return;renderKeys();refreshPreview()}
function build(){if(root)return;root=document.createElement('section');root.id='posix-mobile-keyboard';root.className='posix-mobile-keyboard';root.setAttribute('aria-label','POSIX.js experimental mobile keyboard');const head=document.createElement('div');head.className='pmk-head';const title=document.createElement('strong');title.textContent='POSIX Mobile Keyboard';const previewEl=document.createElement('pre');previewEl.className='pmk-preview';const body=document.createElement('div');body.className='pmk-body';head.append(title);root.append(head,previewEl,body);document.body.append(root);render();const I=input();I?.addEventListener('input',refreshPreview);I?.addEventListener('click',refreshPreview);I?.addEventListener('keyup',refreshPreview)}
function apply(v){const I=input();if(!I)return false;if(v){build();root.hidden=false;document.body.classList.add('mobilemode');I.inputMode='none';I.readOnly=true;I.autocomplete='off';I.setAttribute('aria-label','POSIX.js command input using custom mobile keyboard');try{I.blur()}catch{}refreshPreview()}else{if(root)root.hidden=true;document.body.classList.remove('mobilemode');I.readOnly=false;I.inputMode='text'}setStored(v);return v}
function init(){apply(enabled());if(window.visualViewport){const sync=()=>document.documentElement.style.setProperty('--pmk-vh',window.visualViewport.height+'px');sync();window.visualViewport.addEventListener('resize',sync)}}
window.POSIXLabsMobile={enabled,apply,init,get active(){return enabled()},refresh:refreshPreview};
})();
