(()=>{'use strict';
const S=window.POSIXShell,P=S.P,out=S.out;
S.register('date',async({a})=>{if(a.length)throw Error('usage: date');out(new Date().toString())});
S.register('uptime',async()=>{let s=Math.floor((Date.now()-P.boot)/1000),d=Math.floor(s/86400);s%=86400;let h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60),sec=s%60;out('up '+(d?d+' day'+(d===1?'':'s')+', ':'')+[h,m,sec].map(x=>String(x).padStart(2,'0')).join(':'))});
S.register('hostname',async({a,root})=>{let f=P.fs.get('/etc/hostname');if(!a.length)return out(String(f?.d||'posixjs').trim());if(a.length!==1)throw Error('usage: hostname [NAME]');if(!root)throw Error('permission denied: use sudo hostname NAME');if(!/^[A-Za-z0-9.-]{1,63}$/.test(a[0]))throw Error('invalid hostname');P.write('/etc/hostname',a[0]+'\n');out(a[0])});
S.register('env',async({a,root})=>{if(a.length)throw Error('usage: env');out('USER='+(root?'root':'user'));out('HOME='+(root?'/root':'/home/user'));out('SHELL=/bin/sh');out('PWD='+P.cwd);out('PATH=/bin:/usr/bin:/sbin:/usr/sbin');out('TERM=posixjs');out('POSIX_VERSION='+P.VERSION)});
S.register('true',async()=>{});
S.register('false',async()=>{throw Error('false returned exit status 1')});
S.register('sleep',async({a})=>{if(a.length!==1)throw Error('usage: sleep SECONDS');let s=Number(a[0]);if(!Number.isFinite(s)||s<0||s>60)throw Error('seconds must be between 0 and 60');await new Promise(r=>setTimeout(r,s*1000))});
S.register('seq',async({a})=>{if(a.length<1||a.length>3)throw Error('usage: seq [FIRST [STEP]] LAST');let first=1,step=1,last;if(a.length===1)last=Number(a[0]);else if(a.length===2){first=Number(a[0]);last=Number(a[1])}else{first=Number(a[0]);step=Number(a[1]);last=Number(a[2])}if(![first,step,last].every(Number.isFinite)||step===0)throw Error('invalid number');let vals=[],limit=10000;if(step>0)for(let x=first;x<=last&&vals.length<limit;x+=step)vals.push(x);else for(let x=first;x>=last&&vals.length<limit;x+=step)vals.push(x);if(vals.length===limit)throw Error('sequence too large');out(vals.join('\n'))});
S.register('printf',async({a})=>{if(!a.length)throw Error('usage: printf FORMAT [ARG...]');let fmt=a.shift(),i=0,text=fmt.replace(/%[sd%]/g,m=>m==='%%'?'%':m==='%d'?String(Number(a[i++]||0)):String(a[i++]??'')).replace(/\\n/g,'\n').replace(/\\t/g,'\t');S.raw(text)});
S.register('id',async({root})=>out(root?'uid=0(root) gid=0(root) groups=0(root)':'uid=1000(user) gid=1000(user) groups=1000(user)'));
})();
