(()=>{'use strict';
const S=window.POSIXShell,P=S.P,out=S.out;
function sizeOf(path){let p=P.norm(path),n=P.fs.get(p);if(!n)return 0;if(n.t==='b')return n.d?.byteLength||0;if(n.t==='f')return new TextEncoder().encode(String(n.d||'')).length;if(n.t==='l')return String(n.target||'').length;let q=p==='/'?'/':p+'/',sum=0;for(let[k,x]of P.fs)if(k.startsWith(q)){if(x.t==='b')sum+=x.d?.byteLength||0;else if(x.t==='f')sum+=new TextEncoder().encode(String(x.d||'')).length;else if(x.t==='l')sum+=String(x.target||'').length}return sum}
S.register('which',async({a})=>{if(!a.length)throw Error('usage: which COMMAND...');for(let c of a){if(S.commands.has(c)){out('/bin/'+c);continue}let paths=[c.startsWith('/')?c:'/bin/'+c,'/usr/bin/'+c,'/sbin/'+c,'/usr/sbin/'+c],p=paths.find(x=>P.fs.has(P.norm(x)));if(p)out(P.norm(p));else throw Error(c+': not found')}});
S.register('type',async({a})=>{if(!a.length)throw Error('usage: type COMMAND...');for(let c of a){if(S.commands.has(c))out(c+' is a shell builtin');else{let paths=[c.startsWith('/')?c:'/bin/'+c,'/usr/bin/'+c,'/sbin/'+c,'/usr/sbin/'+c],p=paths.find(x=>P.fs.has(P.norm(x)));if(p)out(c+' is '+P.norm(p));else throw Error(c+': not found')}}});
S.register('history',async({a})=>{if(a.length)throw Error('usage: history');S.history.forEach((x,i)=>out(String(i+1).padStart(4)+'  '+x))});
S.register('du',async({a})=>{let paths=a.length?a:['.'];for(let p of paths){let q=P.norm(p);if(!P.fs.has(q))throw Error(p+': No such file or directory');out(P.fmt(sizeOf(q))+'\t'+q)}});
S.register('df',async({a})=>{if(a.length)throw Error('usage: df');let used=sizeOf('/'),limit=256*1024*1024,free=Math.max(0,limit-used),pct=Math.min(100,Math.round(used/limit*100));out('Filesystem       Size       Used      Avail Use% Mounted on');out('indexeddb       '+P.fmt(limit).padStart(8)+' '+P.fmt(used).padStart(10)+' '+P.fmt(free).padStart(10)+' '+String(pct).padStart(3)+'% /')});
S.register('sort',async({a})=>{if(a.length!==1)throw Error('usage: sort FILE');let p=P.resolve(a[0]),n=P.fs.get(p);if(!n)throw Error(a[0]+': No such file or directory');if(n.t==='d')throw Error(a[0]+': is a directory');let text=n.t==='b'?new TextDecoder().decode(n.d):String(n.d||'');out(text.split('\n').sort((x,y)=>x.localeCompare(y)).join('\n'))});
})();
