(()=>{'use strict';
const S=window.POSIXShell,P=S.P,out=S.out;
const need=(a,msg)=>{if(!a.length)throw Error(msg)};
const node=p=>{let q=P.resolve(p),n=P.fs.get(q);if(!n)throw Error(p+': No such file or directory');return[q,n]};
const parent=p=>P.norm(p).split('/').slice(0,-1).join('/')||'/';
const bytes=n=>n?.t==='b'?(n.d?.byteLength||0):n?.t==='f'?new TextEncoder().encode(String(n.d||'')).length:0;
function cloneEntry(n){if(n.t==='b')return{...n,d:new Uint8Array(n.d||0),time:Date.now()};return{...n,time:Date.now()}}
function copyTree(src,dst){let [sp,sn]=node(src),dp=P.norm(dst);if(sn.t!=='d'){P.md(parent(dp));P.fs.set(dp,cloneEntry(sn));return}P.md(dp);let prefix=sp==='/'?'/':sp+'/';for(let [k,n] of [...P.fs])if(k.startsWith(prefix)){let rel=k.slice(prefix.length),to=P.norm(dp+'/'+rel);if(n.t==='d')P.md(to);else{P.md(parent(to));P.fs.set(to,cloneEntry(n))}}}
function removeTree(path){let p=P.norm(path),n=P.fs.get(p);if(!n)throw Error(path+': No such file or directory');if(p==='/')throw Error('refusing to remove /');let prefix=p+'/';for(let k of [...P.fs.keys()])if(k===p||k.startsWith(prefix))P.fs.delete(k)}
S.register('touch',async({a})=>{need(a,'usage: touch FILE...');for(let f of a){let p=P.norm(f),n=P.fs.get(p);if(n)n.time=Date.now();else P.write(p,'')}});
S.register('rm',async({a})=>{need(a,'usage: rm [-r] FILE...');let recursive=a[0]==='-r'||a[0]==='-rf'||a[0]==='-fr';if(recursive)a.shift();need(a,'usage: rm [-r] FILE...');for(let f of a){let [p,n]=node(f);if(n.t==='d'&&!recursive)throw Error(f+': is a directory');removeTree(p)}});
S.register('rmdir',async({a})=>{need(a,'usage: rmdir DIR...');for(let d of a){let [p,n]=node(d);if(n.t!=='d')throw Error(d+': Not a directory');if(P.ls(p).length)throw Error(d+': Directory not empty');if(p==='/')throw Error('cannot remove /');P.fs.delete(p)}});
S.register('cp',async({a})=>{let recursive=a[0]==='-r'||a[0]==='-R';if(recursive)a.shift();if(a.length!==2)throw Error('usage: cp [-r] SOURCE DEST');let [sp,sn]=node(a[0]),dest=P.norm(a[1]),dn=P.fs.get(dest);if(sn.t==='d'&&!recursive)throw Error('omitting directory '+a[0]);if(dn?.t==='d')dest=P.norm(dest+'/'+sp.split('/').pop());copyTree(sp,dest)});
S.register('mv',async({a})=>{if(a.length!==2)throw Error('usage: mv SOURCE DEST');let [sp,sn]=node(a[0]),dest=P.norm(a[1]),dn=P.fs.get(dest);if(dn?.t==='d')dest=P.norm(dest+'/'+sp.split('/').pop());if(dest===sp)return;if(sn.t==='d'&&dest.startsWith(sp+'/'))throw Error('cannot move a directory into itself');copyTree(sp,dest);removeTree(sp)});
S.register('head',async({a})=>{need(a,'usage: head [-n N] FILE');let n=10;if(a[0]==='-n'){n=Number(a[1]);a=a.slice(2)}if(!Number.isFinite(n)||n<0)throw Error('invalid line count');let[,f]=node(a[0]);if(f.t==='d')throw Error('is a directory');let text=f.t==='b'?new TextDecoder().decode(f.d):String(f.d||'');out(text.split('\n').slice(0,n).join('\n'))});
S.register('tail',async({a})=>{need(a,'usage: tail [-n N] FILE');let n=10;if(a[0]==='-n'){n=Number(a[1]);a=a.slice(2)}if(!Number.isFinite(n)||n<0)throw Error('invalid line count');let[,f]=node(a[0]);if(f.t==='d')throw Error('is a directory');let text=f.t==='b'?new TextDecoder().decode(f.d):String(f.d||'');out(text.split('\n').slice(-n).join('\n'))});
S.register('wc',async({a})=>{need(a,'usage: wc FILE');for(let f of a){let[,n]=node(f);if(n.t==='d')throw Error(f+': is a directory');let text=n.t==='b'?new TextDecoder().decode(n.d):String(n.d||''),lines=text.length?(text.match(/\n/g)||[]).length+(text.endsWith('\n')?0:1):0,words=(text.trim().match(/\S+/g)||[]).length;out(lines+' '+words+' '+bytes(n)+' '+f)}});
S.register('basename',async({a})=>{need(a,'usage: basename PATH');let p=P.norm(a[0]);out(p==='/'?'/':p.split('/').pop())});
S.register('dirname',async({a})=>{need(a,'usage: dirname PATH');out(parent(a[0]))});
S.register('stat',async({a})=>{need(a,'usage: stat FILE...');for(let f of a){let[p,n]=node(f),kind=n.t==='d'?'directory':n.t==='l'?'symbolic link':n.t==='b'?'binary file':'file';out('  File: '+p+'\n  Type: '+kind+'\n  Size: '+bytes(n)+' bytes\nModify: '+new Date(n.time||0).toISOString()+(n.t==='l'?'\n  Link: '+n.target:''))}});
S.register('readlink',async({a})=>{need(a,'usage: readlink FILE');let p=P.norm(a[0]),n=P.fs.get(p);if(!n)throw Error(a[0]+': No such file or directory');if(n.t!=='l')throw Error(a[0]+': Invalid argument');out(n.target)});
S.register('ln',async({a})=>{if(a[0]!=='-s'||a.length!==3)throw Error('usage: ln -s TARGET LINK');let link=P.norm(a[2]);if(P.fs.has(link))throw Error(a[2]+': File exists');P.md(parent(link));P.fs.set(link,{t:'l',target:a[1],time:Date.now()})});
S.register('tree',async({a})=>{let root=P.norm(a[0]||'.'),rn=P.fs.get(root);if(!rn)throw Error(root+': No such file or directory');out(root);if(rn.t!=='d')return;const walk=(dir,prefix)=>{let names=P.ls(dir);for(let i=0;i<names.length;i++){let last=i===names.length-1,name=names[i],p=P.norm(dir+'/'+name),n=P.fs.get(p);out(prefix+(last?'└── ':'├── ')+name+(n?.t==='l'?' -> '+n.target:''));if(n?.t==='d')walk(p,prefix+(last?'    ':'│   '))}};walk(root,'')});
})();
