(()=>{'use strict';
const P=window.POSIX,O=document.querySelector('#o'),I=document.querySelector('#c'),Q=document.querySelector('#p');
const S=window.POSIXShell={P,O,I,Q,history:[],historyIndex:0,commands:new Map};
S.out=s=>{O.textContent+=String(s??'')+'\n';O.scrollTop=O.scrollHeight};
S.raw=s=>{O.textContent+=String(s??'');O.scrollTop=O.scrollHeight};
S.prompt=()=>Q.textContent='user@posixjs:'+P.cwd.replace('/home/user','~')+'$';
S.parse=line=>(line.match(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g)||[]).map(x=>x.replace(/^['"]|['"]$/g,''));
S.register=(name,fn)=>S.commands.set(name,fn);
S.run=async(line,root=false)=>{let parts=S.parse(line);if(!parts.length)return;let command=parts.shift(),fn=S.commands.get(command);try{if(fn)await fn({a:parts,root,command});else{let paths=[command.startsWith('/')?command:'/bin/'+command,'/usr/bin/'+command,'/sbin/'+command,'/usr/sbin/'+command],p=paths.find(x=>P.fs.has(P.norm(x)));if(p)S.out('\n[exit '+await P.exec(p,parts,S.raw)+']');else S.out(command+': command not found')}}catch(e){S.out(command+': '+e.message)}S.prompt()};
})();
