(()=>{'use strict';const P=POSIX;let desktop=null,z=100,seq=0,mode='desktop';const apps=new Map,wlWindows=new Map;const make=(tag,cls,text)=>{let e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e};
function focus(w){if(!desktop||!w)return;for(let x of desktop.querySelectorAll('.uide-window'))x.classList.remove('active');w.classList.add('active');w.style.zIndex=String(++z)}
function draggable(w,head){let drag=null;const move=e=>{if(!drag||mode==='mobile'||w.classList.contains('maximized'))return;let x=Math.max(4,Math.min(innerWidth-w.offsetWidth-4,e.clientX-drag.dx)),y=Math.max(50,Math.min(innerHeight-w.offsetHeight-8,e.clientY-drag.dy));w.style.left=x+'px';w.style.top=y+'px'};head.addEventListener('pointerdown',e=>{if(e.target.closest('button')||mode==='mobile')return;focus(w);let r=w.getBoundingClientRect();drag={dx:e.clientX-r.left,dy:e.clientY-r.top};head.setPointerCapture?.(e.pointerId)});head.addEventListener('pointermove',move);head.addEventListener('pointerup',()=>drag=null);head.addEventListener('pointercancel',()=>drag=null)}
function win(title,body,id){if(!desktop)return null;let w=make('section','uide-window'),head=make('header','uide-window-head'),t=make('div','uide-window-title',title),sp=make('div','uide-window-spacer'),min=make('button','uide-min','–'),max=make('button','uide-max','□'),x=make('button','uide-close','×'),content=make('div','uide-window-body');min.title='Minimize';max.title='Maximize';x.title='Close';min.onclick=()=>w.classList.toggle('minimized');max.onclick=()=>{w.classList.toggle('maximized');max.textContent=w.classList.contains('maximized')?'❐':'□';focus(w)};x.onclick=()=>{w.remove();if(id!==undefined)wlWindows.delete(id)};head.append(t,sp,min,max,x);content.append(body);w.append(head,content);if(mode!=='mobile'){w.style.left=(110+(seq%6)*28)+'px';w.style.top=(70+(seq%5)*24)+'px'}seq++;desktop.querySelector('.uide-space').append(w);draggable(w,head);w.addEventListener('pointerdown',()=>focus(w));focus(w);if(id!==undefined)wlWindows.set(id,{w,title:t,content});return w}
function toast(text){if(!desktop)return;desktop.querySelector('.uide-toast')?.remove();let e=make('div','uide-toast',text);desktop.append(e);setTimeout(()=>e.remove(),2800)}
function registerApp(id,app){apps.set(id,app)}
function launch(id){let a=apps.get(id);if(!a)return toast('App unavailable: '+id);try{a.open()}catch(e){toast(a.name+': '+e.message)}}
function buildDock(){let dock=make('nav','uide-dock');for(let[id,a]of apps){if(a.dock===false)continue;let b=make('button','',a.icon||a.name.slice(0,1));b.title=a.name;b.onclick=()=>launch(id);dock.append(b)}let launcher=make('button','','⌘');launcher.title='All apps';launcher.onclick=()=>{let panel=desktop.querySelector('.uide-launcher');if(panel)return panel.remove();panel=make('div','uide-launcher');for(const[id,a]of apps){let b=make('button','uide-launcher-app',(a.icon||'◻')+'  '+a.name);b.onclick=()=>{panel.remove();launch(id)};panel.append(b)}desktop.append(panel)};let exit=make('button','','⏻');exit.title='Exit UIDE';exit.onclick=close;dock.prepend(launcher);dock.append(exit);return dock}
function buildDesktopIcons(space){let wrap=make('div','uide-desktop-icons');for(let[id,a]of apps){if(a.desktop===false)continue;let b=make('button','uide-desktop-icon'),i=make('span','',a.icon||'◻'),n=make('span','',a.name);b.append(i,n);b.ondblclick=()=>launch(id);b.onclick=()=>{if(matchMedia('(pointer:coarse)').matches)launch(id)};wrap.append(b)}space.append(wrap)}
function start(out=()=>{},requestedMode='desktop'){if(desktop)return out('uide: already running');mode=requestedMode==='mobile'?'mobile':'desktop';P.md('/run/user/1000');P.md('/dev/shm');desktop=make('div','uide');let top=make('header','uide-top'),brand=make('span','uide-brand','POSIX.js '+P.VERSION),space=make('main','uide-space');top.append(brand);desktop.append(top,space);if(mode==='desktop'){buildDesktopIcons(space);desktop.append(buildDock())}document.body.append(desktop);document.body.classList.add('uide-open');if(mode==='mobile'){window.UIDEMobile?.decorate?.(desktop,window.UIDE)}out('UIDE '+P.VERSION+' '+mode+' started · '+apps.size+' apps')}
function close(){window.UIDEMobile?.cleanup?.();desktop?.remove();desktop=null;wlWindows.clear();document.body.classList.remove('uide-open');document.querySelector('#c')?.focus()}
P.uide=async(a,out)=>{let op=a.shift()||'status';if(op==='start')return start(out,'desktop');if(op==='mobile')return start(out,'mobile');if(op==='stop'){close();return out('UIDE stopped')}if(op==='status')return out('UIDE '+P.VERSION+' · '+(desktop?mode:'inactive')+' · apps '+apps.size+' · Wayland '+(window.POSIXWayland?.version||'off'));if(op==='apps'){for(let[id,x]of apps)out(id+' · '+x.name);return}if(op==='open'){let id=a.shift();if(!id)throw Error('usage: uide open <app>');if(!apps.has(id))throw Error('unknown UIDE app: '+id);if(!desktop)start(()=>{},matchMedia('(max-width:700px)').matches?'mobile':'desktop');launch(id);return}if(op==='dev'){if(!desktop)start(()=>{},'desktop');return launch('developer')}if(op==='rpt')return out('rpt://quilt-studios.github.io/rpt · browser-local transport');if(op==='wayland')return out('Wayland socket: /run/user/1000/wayland-0 · shm canvas bridge');out('uide: start | mobile | stop | status | apps | open <app> | dev | rpt | wayland')};
window.UIDE={VERSION:P.VERSION,start,close,win,toast,registerApp,launch,apps,wlWindows,get desktop(){return desktop},get mode(){return mode},make}})();
