(()=>{'use strict';
const S=POSIXShell,P=S.P,out=S.out;
const enc=new TextEncoder();
const typeOf=n=>n?.t==='d'?'d':n?.t==='l'?'l':n?.t==='b'?'b':'-';
const byteSize=n=>n?.t==='b'?(n.d?.byteLength||0):n?.t==='f'?enc.encode(String(n.d||'')).length:n?.t==='l'?enc.encode(String(n.target||'')).length:0;
const human=n=>n<1024?n+'B':n<1048576?(n/1024).toFixed(n<10240?1:0)+'K':(n/1048576).toFixed(n<10485760?1:0)+'M';
const executable=(path,n)=>n?.t==='b'&&(/^\/(bin|sbin)\//.test(path)||/^\/usr\/(bin|sbin)\//.test(path)||((n.d?.[0]===0x7f)&&(n.d?.[1]===0x45)&&(n.d?.[2]===0x4c)&&(n.d?.[3]===0x46)));
const mode=(path,n)=>{const t=typeOf(n);if(t==='d')return'drwxr-xr-x';if(t==='l')return'lrwxrwxrwx';return executable(path,n)?'-rwxr-xr-x':'-rw-r--r--'};
const stamp=n=>{const d=new Date(n?.time||0);if(!Number.isFinite(d.getTime())||!n?.time)return'            ';const mon=d.toLocaleString('en',{month:'short'}),day=String(d.getDate()).padStart(2,' '),hm=String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');return mon+' '+day+' '+hm};
const directChildren=dir=>{const prefix=dir==='/'?'/':dir+'/',seen=new Map;for(const [path,node] of P.fs){if(path===dir||!path.startsWith(prefix))continue;const rest=path.slice(prefix.length),name=rest.split('/')[0];if(!name||seen.has(name))continue;const childPath=P.norm(prefix+name),child=P.fs.get(childPath);seen.set(name,{name,path:childPath,node:child||node})}return[...seen.values()]};
const cmp=(a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'});
function parse(argv){const o={all:false,almost:false,long:false,human:false,one:false,classify:false,recursive:false,icons:null,paths:[]};let options=true;for(const arg of argv){if(options&&arg==='--'){options=false;continue}if(options&&arg.startsWith('--')){if(arg==='--all')o.all=true;else if(arg==='--almost-all')o.almost=true;else if(arg==='--long')o.long=true;else if(arg==='--human-readable')o.human=true;else if(arg==='--classify')o.classify=true;else if(arg==='--recursive')o.recursive=true;else if(arg==='--icons')o.icons=true;else if(arg==='--no-icons')o.icons=false;else if(arg==='--help')o.help=true;else throw Error('unrecognized option '+arg);continue}if(options&&arg.startsWith('-')&&arg!=='-'){for(const c of arg.slice(1)){if(c==='a')o.all=true;else if(c==='A')o.almost=true;else if(c==='l')o.long=true;else if(c==='h')o.human=true;else if(c==='1')o.one=true;else if(c==='F')o.classify=true;else if(c==='R')o.recursive=true;else throw Error('invalid option -- '+c)}continue}o.paths.push(arg)}if(!o.paths.length)o.paths=['.'];return o}
function suffix(path,n){if(n?.t==='d')return'/';if(n?.t==='l')return'@';if(executable(path,n))return'*';return''}
function displayName(entry,o){const nf=window.POSIXNerdFont,useIcons=o.icons===true||(o.icons===null&&nf?.enabled);let name=entry.name;if(o.classify)name+=suffix(entry.path,entry.node);if(useIcons&&nf)return nf.iconFor(entry.name,entry.node)+' '+name;return name}
function longLine(entry,o){const n=entry.node,size=o.human?human(byteSize(n)):String(byteSize(n));let line=mode(entry.path,n)+' 1 user user '+String(size).padStart(8)+' '+stamp(n)+' '+displayName(entry,o);if(n?.t==='l')line+=' -> '+n.target;return line}
function listDir(dir,label,o,visited,printHeader){if(visited.has(dir))return;visited.add(dir);if(printHeader)out(label+':');let entries=directChildren(dir).sort(cmp);if(!o.all&&!o.almost)entries=entries.filter(e=>!e.name.startsWith('.'));if(o.all){entries.unshift({name:'..',path:P.norm(dir+'/..'),node:P.fs.get(P.norm(dir+'/..'))||{t:'d'}});entries.unshift({name:'.',path:dir,node:P.fs.get(dir)||{t:'d'}})}if(o.long){for(const e of entries)out(longLine(e,o))}else if(o.one){for(const e of entries)out(displayName(e,o))}else if(entries.length){out(entries.map(e=>displayName(e,o)).join('  '))}if(o.recursive){for(const e of entries){if(e.name==='.'||e.name==='..'||e.node?.t!=='d')continue;out('');listDir(e.path,e.path,o,visited,true)}}}
S.register('ls',async({a})=>{const o=parse(a);if(o.help){out('usage: ls [-aAlh1FR] [--icons|--no-icons] [FILE...]');out('  -a all  -A almost-all  -l long  -h human sizes  -1 one per line');out('  -F classify  -R recursive');return}const multiple=o.paths.length>1,visited=new Set;for(let i=0;i<o.paths.length;i++){const arg=o.paths[i],raw=P.norm(arg),rawNode=P.fs.get(raw);let path=raw,node=rawNode;if(!node){try{path=P.resolve(raw);node=P.fs.get(path)}catch(e){throw Error(arg+': '+e.message)}}if(!node)throw Error(arg+': No such file or directory');if(i&&multiple)out('');if(node.t==='d'){listDir(path,arg,o,visited,multiple)}else{const e={name:raw==='/'?'/':raw.split('/').pop(),path:raw,node};out(o.long?longLine(e,o):displayName(e,o))}}});
})();
